In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
df_artists = pd.read_csv(r'/home/agastya/Documents/Python/Praxis/ML/Personal Practice/Spotify_Project/data/data_by_artist.csv', ',')

In [3]:
df_genres = pd.read_csv(r'/home/agastya/Documents/Python/Praxis/ML/Personal Practice/Spotify_Project/data/data_by_genres.csv', ',')

In [4]:
df_w_genres = pd.read_csv(r'/home/agastya/Documents/Python/Praxis/ML/Personal Practice/Spotify_Project/data/data_w_genres.csv', ',')

In [5]:
# Drop Unnamed column
df_w_genres.drop('Unnamed: 0', axis=1, inplace=True)

In [6]:
# Convert genres from string to list 
import re
pattern = re.compile(r'\w+\s*?\w+', re.IGNORECASE)
df_w_genres['genres'] = df_w_genres['genres'].map(lambda x: re.findall(pattern, x))

In [7]:
# Change fields of no genres to None
df_w_genres['genres'] = df_w_genres['genres'].map(lambda x: np.nan if len(x) == 0 else x)

In [8]:
# Artists with no genres
no_genre_artists = df_w_genres[df_w_genres['genres'].isna()]

In [9]:
no_genre_artists

,artists,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode,count,genres
72,Orchestra Studio 7,0.342315,0.561378,203097.777311,0.392441,0.467496,0.190490,-14.332546,0.054264,116.684315,0.532022,0.021008,5,1,238,NaN
88,Sinclair Lewis,0.691179,0.681108,264736.075472,0.208925,0.000005,0.258333,-19.368524,0.955585,106.152203,0.460193,0.004717,4,1,212,NaN
90,Unspecified,0.812928,0.462446,141540.142180,0.344851,0.377778,0.283078,-18.818299,0.154392,110.679294,0.474366,1.241706,10,1,211,NaN
124,Orchestra Sinfonica di Roma della RAI,0.968614,0.379123,204830.590643,0.193932,0.046241,0.268602,-16.807421,0.103258,103.132047,0.212032,0.000000,10,1,171,NaN
130,Rita Ampatzi,0.953272,0.459373,195420.538462,0.448793,0.331829,0.193202,-9.905633,0.050520,111.843538,0.725680,0.011834,1,1,169,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27589,Rock City,0.096300,0.749000,239973.000000,0.846000,0.012200,0.313000,-7.518000,0.089500,143.004000,0.481000,50.000000,1,1,1,NaN
27592,DMC,0.188000,0.458000,326733.000000,0.824000,0.000000,0.112000,-4.224000,0.519000,86.331000,0.499000,43.000000,11,0,1,NaN
27595,Suzi Benson,0.495000,0.552000,247493.000000,0.391000,0.000000,0.086700,-12.097000,0.034300,131.980000,0.309000,44.000000,2,1,1,NaN
27596,Sam Burtis,0.152000,0.662000,374813.000000,0.764000,0.010300,0.080300,-7.994000,0.081900,135.902000,0.769000,31.000000,7,1,1,NaN
27599,Nazir,0.993000,0.775000,160473.000000,0.280000,0.195000,0.140000,-9.225000,0.308000,84.947000,0.906000,0.000000,5,1,1,NaN

In [10]:
# For next code cells
def standardize_tempo_for_genre(x):
    min_tempo = df_genres['tempo'].min()
    max_tempo = df_genres['tempo'].max()
    return (x-min_tempo)/(max_tempo-min_tempo)

In [11]:
def standardize_tempo_for_artist(x):
    min_tempo = no_genre_artists['tempo'].min()
    max_tempo = no_genre_artists['tempo'].max()
    return (x-min_tempo)/(max_tempo-min_tempo)

In [47]:
# Try 1 - [acousticness, danceability, instrumentalness, tempo, valence]

try_1_genres = df_genres.loc[:, ['acousticness', 'danceability', 'instrumentalness', 'tempo', 'valence']]
try_1_genres['tempo'] = try_1_genres['tempo'].map(standardize_tempo_for_genre)

try_1_artists = no_genre_artists.loc[:, ['acousticness', 'danceability', 'instrumentalness', 'tempo', 'valence']]
try_1_artists['tempo'] = try_1_artists['tempo'].map(standardize_tempo_for_artist)

try_1_artists = np.array(try_1_artists)
try_1_genres = np.array(try_1_genres)

In [55]:
artist_genre_distance_try_1 = []
artist_genre_indexes_try_1 = []

for artist_feature in try_1_artists:
    distance_vals = []
    for genre_feature in try_1_genres:
        distance_vals.append(np.linalg.norm(artist_feature-genre_feature))
    # Take only top 10
    distance_vals = np.array(distance_vals)
    
    artist_genre_distance_try_1.append(distance_vals[distance_vals.argsort()][:10])
    artist_genre_indexes_try_1.append(distance_vals.argsort()[:10])

In [63]:
no_genre_artists.iloc[0]

artists             Orchestra Studio 7
acousticness                  0.342315
danceability                  0.561378
duration_ms                     203098
energy                        0.392441
instrumentalness              0.467496
liveness                       0.19049
loudness                      -14.3325
speechiness                  0.0542639
tempo                          116.684
valence                       0.532022
popularity                   0.0210084
key                                  5
mode                                 1
count                              238
genres                             NaN
Name: 72, dtype: object

In [64]:
df_genres.iloc[artist_genre_indexes_try_1[0]]

,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode
2057,rhode island indie,0.248761,0.505667,188386.166667,0.728417,0.439298,0.148358,-8.770500,0.058208,132.339750,0.581667,41.083333,4,1
331,british industrial,0.260124,0.596156,253703.606803,0.632908,0.501976,0.157053,-13.414348,0.061914,121.039166,0.560386,29.080612,0,1
231,belgian indie,0.467000,0.564250,286366.500000,0.688750,0.486250,0.100200,-8.171500,0.036225,129.002000,0.506000,46.500000,10,1
259,bleep techno,0.243382,0.572361,273238.888889,0.736333,0.507456,0.208069,-8.836778,0.069403,130.764778,0.614436,43.555556,11,1
1605,modern dream pop,0.408820,0.535250,250775.749036,0.596949,0.386814,0.137330,-8.953715,0.037197,124.788873,0.462639,49.222039,2,1
1240,instrumental soul,0.381695,0.602435,252408.701452,0.539435,0.518661,0.135659,-11.004841,0.047014,115.386640,0.607844,32.983241,10,1
1865,palm desert scene,0.203318,0.482522,232229.779894,0.737249,0.427242,0.192502,-8.504152,0.056501,126.326448,0.528291,44.356878,9,1
797,downtempo,0.266034,0.603996,297572.058136,0.579686,0.424080,0.166288,-9.493431,0.066456,118.680109,0.429592,49.203524,7,1
2206,smooth jazz,0.337245,0.632402,293887.727558,0.539757,0.417892,0.139156,-10.970289,0.040750,112.243773,0.583466,37.752913,5,1
123,atmospheric post-rock,0.252210,0.668000,331466.500000,0.773500,0.478055,0.144000,-5.724000,0.056000,119.999500,0.483000,23.500000,11,1

In [99]:
# Try 2 - [acousticness, danceability, instrumentalness, tempo,energy, valence, energy]

try_2_genres = df_genres.loc[:, ['acousticness', 'danceability', 'instrumentalness', 'energy', 'tempo', 'valence']]
try_2_genres['tempo'] = try_2_genres['tempo'].map(standardize_tempo_for_genre)

try_2_artists = no_genre_artists.loc[:, ['acousticness', 'danceability', 'instrumentalness', 'energy', 'tempo', 'valence']]
try_2_artists['tempo'] = try_2_artists['tempo'].map(standardize_tempo_for_artist)

try_2_artists = np.array(try_2_artists)
try_2_genres = np.array(try_2_genres)

In [100]:
artist_genre_distance_try_2 = []
artist_genre_indexes_try_2 = []

for artist_feature in try_2_artists:
    distance_vals = []
    for genre_feature in try_2_genres:
        distance_vals.append(np.linalg.norm(artist_feature-genre_feature))
    # Take only top 10
    distance_vals = np.array(distance_vals)
    
    artist_genre_distance_try_2.append(distance_vals[distance_vals.argsort()][:10])
    artist_genre_indexes_try_2.append(distance_vals.argsort()[:10])

In [109]:
df_genres.iloc[artist_genre_indexes_try_1[4]]

,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode
2039,rebetiko,0.959770,0.533861,193814.327377,0.376418,0.336413,0.193219,-11.768717,0.053218,114.612810,0.716307,2.008617,7,1
2535,vintage old-time,0.968875,0.578806,184259.888889,0.267389,0.304343,0.192260,-12.567111,0.069199,122.886611,0.737694,4.125000,10,1
1247,irish banjo,0.837333,0.483000,172618.000000,0.601333,0.248893,0.693333,-11.168333,0.167533,128.974333,0.773667,25.666667,2,1
2541,vintage tango,0.945190,0.564508,177501.059780,0.310706,0.356746,0.243507,-11.680452,0.101448,116.664835,0.643147,4.227987,2,1
1844,orquesta tipica,0.924137,0.607385,163619.052656,0.321117,0.404575,0.291078,-11.650894,0.122958,133.062939,0.700014,4.205128,9,1
418,carnatic vocal,0.907121,0.550103,318522.668240,0.388231,0.253515,0.214114,-11.422840,0.091707,113.549147,0.680970,9.106392,10,1
1079,greek clarinet,0.844585,0.476566,171165.840931,0.522081,0.293887,0.231821,-9.599911,0.067806,110.036666,0.723124,0.000000,2,1
2534,vintage jazz,0.928986,0.610030,183929.619837,0.317587,0.329331,0.225722,-12.599809,0.076543,120.875787,0.654530,6.689927,5,1
1084,greek swing,0.978595,0.571524,191273.166667,0.336893,0.254362,0.230271,-13.069369,0.051024,113.645512,0.683095,0.595238,7,1
517,classic bollywood,0.885505,0.502630,230690.737137,0.354426,0.308211,0.213069,-11.773005,0.097147,109.769526,0.633942,8.191785,7,1

In [10]:
df_w_genres.head(1)

,artists,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode,count,genres
0,Francisco Canaro,0.983072,0.654711,177776.513454,0.292622,0.490675,0.201118,-11.733373,0.111007,123.608786,0.746469,0.054257,2,1,2267,"[tango, vintage tango]"

In [12]:
genre_set = set()
for i in df_w_genres['genres']:
    # print(type(i))
    try:
        genre_set.update(i)
    except(TypeError):
        pass

len(genre_set) # Number of unique genres

2602

In [13]:
df_w_genres[~df_w_genres['genres'].isna()].shape

(18056, 16)

In [14]:
genre_sparse_df = pd.DataFrame(np.zeros((18056, len(genre_set))), columns=genre_set)

In [15]:
index = 0
for i in df_w_genres[~df_w_genres['genres'].isna()]['genres']:
    for j in i:
        genre_sparse_df.loc[index, j] = 1
    index +=1

In [18]:
genre_sparse_df.describe()

,venezuelan hip,idaho indie,vintage swing,slamming deathcore,ninos,chinese idol,memphis hip,danish post,cool jazz,lds youth,...,omaha indie,italian jazz,new americana,historic piano,vegan straight,merseybeat,americana,taiwan campus,orebro indie,ska punk
count,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,...,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000,18056.000000
mean,0.000111,0.000111,0.000332,0.000055,0.000111,0.000055,0.001495,0.000055,0.010467,0.000332,...,0.000222,0.000055,0.008861,0.001551,0.000111,0.005261,0.003821,0.000609,0.000055,0.003711
std,0.010524,0.010524,0.018227,0.007442,0.010524,0.007442,0.038642,0.007442,0.101776,0.018227,...,0.014883,0.007442,0.093719,0.039350,0.010524,0.072347,0.061701,0.024675,0.007442,0.060804
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [68]:
'''from scipy.sparse import csr_matrix, csc_matrix
genre_sparse_csr = csr_matrix(genre_sparse_df
# To save the sparse matrix
with open('csr_matrix', 'wb') as f:
    pickle.dump(genre_sparse_csr, f)'''

In [65]:
# To save the full sparse dataset
# genre_sparse_df.to_pickle('sparse_matrix')

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
training_raw = df_w_genres[~df_w_genres['genres'].isna()]

In [26]:
#try_2_artists['tempo'] = try_2_artists['tempo'].map(standardize_tempo_for_artist)
training_raw = training_raw.loc[:, ['acousticness', 'danceability', 'instrumentalness', 'energy', 'tempo', 'valence']]

In [27]:
training_raw['tempo'] = training_raw['tempo'].map(standardize_tempo_for_artist)

In [16]:
with open('csr_matrix', 'rb') as f:
    genre_sparse_csr = pickle.load(f)

In [19]:
# Use toarray to convert it back to a full set
genre_sparse_csr.toarray().shape

(18056, 2602)

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
rfc = RandomForestClassifier()
rfc.fit(training_raw, genre_sparse_csr.toarray())

NameError: name 'training_raw' is not defined

In [108]:
no_genre_artists.iloc[4]

artists             Rita Ampatzi
acousticness            0.953272
danceability            0.459373
duration_ms               195421
energy                  0.448793
instrumentalness        0.331829
liveness                0.193202
loudness                -9.90563
speechiness            0.0505201
tempo                    111.844
valence                  0.72568
popularity             0.0118343
key                            1
mode                           1
count                        169
genres                       NaN
Name: 130, dtype: object